Reverse a string
alisavch/reverse pull request #1
Opened 2021-05-13 14:24 UTC by alisavch

2021-05-14 11:15 UTC, papahmsolo requested changes
Looks good! Let's improve a bit:

- let's rename `actions.go` to something like `strings.go`
- for simplicity reasons can we drop the `testify` and use just std lib for now as you do?
- let's first merge the reverse functionality and release it as 1.0.0 and only then add capitalize

2021-05-14 11:15 UTC, papahmsolo commented on go.mod
> +)
try `go mod tidy` this looks like a lot of redundant dependencies

2021-05-14 11:15 UTC, papahmsolo commented on actions_test.go
> +}
Not sure why do we have two distinct functions

2021-05-17 13:51 UTC, alisavch commented on README.md
> +- Strings in Go, UTF-8, Unicode
Ok. thanks, changed

2021-05-17 13:52 UTC, alisavch commented on actions.go
> +// Reverse string
Good point, thanks

2021-05-17 13:53 UTC, alisavch commented on actions_test.go
> +}
Really, thanks

2021-05-18 08:33 UTC, papahmsolo commented on strings.go
> +}
- not really a problem, but named return doesn't provide any additional details, so we might just get rid of it.
- it's idiomatic in Go to give short names to variables, like `k, v` for key and value in `range`, check out [this](https://github.com/golang/go/wiki/CodeReviewComments#variable-names)
- can we not use a naked return and rather return the value explicitly?

2021-05-18 08:34 UTC, papahmsolo requested changes
Well done 👍 

Let's address the last minor comments and we can get the first PR merged!

2021-05-18 11:16 UTC, alisavch commented on strings.go
> +}
ok thanks

2021-05-18 12:33 UTC, papahmsolo approved these changes
Looks good 👍

2021-05-18 12:33 UTC, merged